server:
  port: 8888

spring:
  profiles:
    active: ${profile.active}

dubbo:
  # Dubbo 应用名称
  application:
    name: shop-web
  # 注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183